/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TratamientosEquipoIndexRouteImport } from './routes/tratamientosEquipo/index'
import { Route as TheatersIndexRouteImport } from './routes/theaters/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as GenresIndexRouteImport } from './routes/genres/index'
import { Route as ActorsIndexRouteImport } from './routes/actors/index'
import { Route as TratamientosEquipoNewRouteImport } from './routes/tratamientosEquipo/new'
import { Route as TratamientosEquipoIdRouteImport } from './routes/tratamientosEquipo/$id'
import { Route as TheatersNewRouteImport } from './routes/theaters/new'
import { Route as TheatersIdRouteImport } from './routes/theaters/$id'
import { Route as MoviesNewRouteImport } from './routes/movies/new'
import { Route as MoviesIdRouteImport } from './routes/movies/$id'
import { Route as GenresNewRouteImport } from './routes/genres/new'
import { Route as GenresIdRouteImport } from './routes/genres/$id'
import { Route as ActorsNewRouteImport } from './routes/actors/new'
import { Route as ActorsIdRouteImport } from './routes/actors/$id'
import { Route as TratamientosEquipoIdIndexRouteImport } from './routes/tratamientosEquipo/$id/index'
import { Route as TheatersIdIndexRouteImport } from './routes/theaters/$id/index'
import { Route as MoviesIdIndexRouteImport } from './routes/movies/$id/index'
import { Route as GenresIdIndexRouteImport } from './routes/genres/$id/index'
import { Route as ActorsIdIndexRouteImport } from './routes/actors/$id/index'
import { Route as TratamientosEquipoIdEditRouteImport } from './routes/tratamientosEquipo/$id/edit'
import { Route as TheatersIdEditRouteImport } from './routes/theaters/$id/edit'
import { Route as MoviesIdEditRouteImport } from './routes/movies/$id/edit'
import { Route as GenresIdEditRouteImport } from './routes/genres/$id/edit'
import { Route as ActorsIdEditRouteImport } from './routes/actors/$id/edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamientosEquipoIndexRoute = TratamientosEquipoIndexRouteImport.update({
  id: '/tratamientosEquipo/',
  path: '/tratamientosEquipo/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatersIndexRoute = TheatersIndexRouteImport.update({
  id: '/theaters/',
  path: '/theaters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIndexRoute = ActorsIndexRouteImport.update({
  id: '/actors/',
  path: '/actors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamientosEquipoNewRoute = TratamientosEquipoNewRouteImport.update({
  id: '/tratamientosEquipo/new',
  path: '/tratamientosEquipo/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamientosEquipoIdRoute = TratamientosEquipoIdRouteImport.update({
  id: '/tratamientosEquipo/$id',
  path: '/tratamientosEquipo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatersNewRoute = TheatersNewRouteImport.update({
  id: '/theaters/new',
  path: '/theaters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatersIdRoute = TheatersIdRouteImport.update({
  id: '/theaters/$id',
  path: '/theaters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesNewRoute = MoviesNewRouteImport.update({
  id: '/movies/new',
  path: '/movies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresNewRoute = GenresNewRouteImport.update({
  id: '/genres/new',
  path: '/genres/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIdRoute = GenresIdRouteImport.update({
  id: '/genres/$id',
  path: '/genres/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsNewRoute = ActorsNewRouteImport.update({
  id: '/actors/new',
  path: '/actors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIdRoute = ActorsIdRouteImport.update({
  id: '/actors/$id',
  path: '/actors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamientosEquipoIdIndexRoute =
  TratamientosEquipoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TratamientosEquipoIdRoute,
  } as any)
const TheatersIdIndexRoute = TheatersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TheatersIdRoute,
} as any)
const MoviesIdIndexRoute = MoviesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoviesIdRoute,
} as any)
const GenresIdIndexRoute = GenresIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GenresIdRoute,
} as any)
const ActorsIdIndexRoute = ActorsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActorsIdRoute,
} as any)
const TratamientosEquipoIdEditRoute =
  TratamientosEquipoIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => TratamientosEquipoIdRoute,
  } as any)
const TheatersIdEditRoute = TheatersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TheatersIdRoute,
} as any)
const MoviesIdEditRoute = MoviesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MoviesIdRoute,
} as any)
const GenresIdEditRoute = GenresIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => GenresIdRoute,
} as any)
const ActorsIdEditRoute = ActorsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ActorsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/actors/$id': typeof ActorsIdRouteWithChildren
  '/actors/new': typeof ActorsNewRoute
  '/genres/$id': typeof GenresIdRouteWithChildren
  '/genres/new': typeof GenresNewRoute
  '/movies/$id': typeof MoviesIdRouteWithChildren
  '/movies/new': typeof MoviesNewRoute
  '/theaters/$id': typeof TheatersIdRouteWithChildren
  '/theaters/new': typeof TheatersNewRoute
  '/tratamientosEquipo/$id': typeof TratamientosEquipoIdRouteWithChildren
  '/tratamientosEquipo/new': typeof TratamientosEquipoNewRoute
  '/actors': typeof ActorsIndexRoute
  '/genres': typeof GenresIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/theaters': typeof TheatersIndexRoute
  '/tratamientosEquipo': typeof TratamientosEquipoIndexRoute
  '/actors/$id/edit': typeof ActorsIdEditRoute
  '/genres/$id/edit': typeof GenresIdEditRoute
  '/movies/$id/edit': typeof MoviesIdEditRoute
  '/theaters/$id/edit': typeof TheatersIdEditRoute
  '/tratamientosEquipo/$id/edit': typeof TratamientosEquipoIdEditRoute
  '/actors/$id/': typeof ActorsIdIndexRoute
  '/genres/$id/': typeof GenresIdIndexRoute
  '/movies/$id/': typeof MoviesIdIndexRoute
  '/theaters/$id/': typeof TheatersIdIndexRoute
  '/tratamientosEquipo/$id/': typeof TratamientosEquipoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/actors/new': typeof ActorsNewRoute
  '/genres/new': typeof GenresNewRoute
  '/movies/new': typeof MoviesNewRoute
  '/theaters/new': typeof TheatersNewRoute
  '/tratamientosEquipo/new': typeof TratamientosEquipoNewRoute
  '/actors': typeof ActorsIndexRoute
  '/genres': typeof GenresIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/theaters': typeof TheatersIndexRoute
  '/tratamientosEquipo': typeof TratamientosEquipoIndexRoute
  '/actors/$id/edit': typeof ActorsIdEditRoute
  '/genres/$id/edit': typeof GenresIdEditRoute
  '/movies/$id/edit': typeof MoviesIdEditRoute
  '/theaters/$id/edit': typeof TheatersIdEditRoute
  '/tratamientosEquipo/$id/edit': typeof TratamientosEquipoIdEditRoute
  '/actors/$id': typeof ActorsIdIndexRoute
  '/genres/$id': typeof GenresIdIndexRoute
  '/movies/$id': typeof MoviesIdIndexRoute
  '/theaters/$id': typeof TheatersIdIndexRoute
  '/tratamientosEquipo/$id': typeof TratamientosEquipoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/actors/$id': typeof ActorsIdRouteWithChildren
  '/actors/new': typeof ActorsNewRoute
  '/genres/$id': typeof GenresIdRouteWithChildren
  '/genres/new': typeof GenresNewRoute
  '/movies/$id': typeof MoviesIdRouteWithChildren
  '/movies/new': typeof MoviesNewRoute
  '/theaters/$id': typeof TheatersIdRouteWithChildren
  '/theaters/new': typeof TheatersNewRoute
  '/tratamientosEquipo/$id': typeof TratamientosEquipoIdRouteWithChildren
  '/tratamientosEquipo/new': typeof TratamientosEquipoNewRoute
  '/actors/': typeof ActorsIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/theaters/': typeof TheatersIndexRoute
  '/tratamientosEquipo/': typeof TratamientosEquipoIndexRoute
  '/actors/$id/edit': typeof ActorsIdEditRoute
  '/genres/$id/edit': typeof GenresIdEditRoute
  '/movies/$id/edit': typeof MoviesIdEditRoute
  '/theaters/$id/edit': typeof TheatersIdEditRoute
  '/tratamientosEquipo/$id/edit': typeof TratamientosEquipoIdEditRoute
  '/actors/$id/': typeof ActorsIdIndexRoute
  '/genres/$id/': typeof GenresIdIndexRoute
  '/movies/$id/': typeof MoviesIdIndexRoute
  '/theaters/$id/': typeof TheatersIdIndexRoute
  '/tratamientosEquipo/$id/': typeof TratamientosEquipoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/actors/$id'
    | '/actors/new'
    | '/genres/$id'
    | '/genres/new'
    | '/movies/$id'
    | '/movies/new'
    | '/theaters/$id'
    | '/theaters/new'
    | '/tratamientosEquipo/$id'
    | '/tratamientosEquipo/new'
    | '/actors'
    | '/genres'
    | '/movies'
    | '/theaters'
    | '/tratamientosEquipo'
    | '/actors/$id/edit'
    | '/genres/$id/edit'
    | '/movies/$id/edit'
    | '/theaters/$id/edit'
    | '/tratamientosEquipo/$id/edit'
    | '/actors/$id/'
    | '/genres/$id/'
    | '/movies/$id/'
    | '/theaters/$id/'
    | '/tratamientosEquipo/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/actors/new'
    | '/genres/new'
    | '/movies/new'
    | '/theaters/new'
    | '/tratamientosEquipo/new'
    | '/actors'
    | '/genres'
    | '/movies'
    | '/theaters'
    | '/tratamientosEquipo'
    | '/actors/$id/edit'
    | '/genres/$id/edit'
    | '/movies/$id/edit'
    | '/theaters/$id/edit'
    | '/tratamientosEquipo/$id/edit'
    | '/actors/$id'
    | '/genres/$id'
    | '/movies/$id'
    | '/theaters/$id'
    | '/tratamientosEquipo/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/actors/$id'
    | '/actors/new'
    | '/genres/$id'
    | '/genres/new'
    | '/movies/$id'
    | '/movies/new'
    | '/theaters/$id'
    | '/theaters/new'
    | '/tratamientosEquipo/$id'
    | '/tratamientosEquipo/new'
    | '/actors/'
    | '/genres/'
    | '/movies/'
    | '/theaters/'
    | '/tratamientosEquipo/'
    | '/actors/$id/edit'
    | '/genres/$id/edit'
    | '/movies/$id/edit'
    | '/theaters/$id/edit'
    | '/tratamientosEquipo/$id/edit'
    | '/actors/$id/'
    | '/genres/$id/'
    | '/movies/$id/'
    | '/theaters/$id/'
    | '/tratamientosEquipo/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  ActorsIdRoute: typeof ActorsIdRouteWithChildren
  ActorsNewRoute: typeof ActorsNewRoute
  GenresIdRoute: typeof GenresIdRouteWithChildren
  GenresNewRoute: typeof GenresNewRoute
  MoviesIdRoute: typeof MoviesIdRouteWithChildren
  MoviesNewRoute: typeof MoviesNewRoute
  TheatersIdRoute: typeof TheatersIdRouteWithChildren
  TheatersNewRoute: typeof TheatersNewRoute
  TratamientosEquipoIdRoute: typeof TratamientosEquipoIdRouteWithChildren
  TratamientosEquipoNewRoute: typeof TratamientosEquipoNewRoute
  ActorsIndexRoute: typeof ActorsIndexRoute
  GenresIndexRoute: typeof GenresIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  TheatersIndexRoute: typeof TheatersIndexRoute
  TratamientosEquipoIndexRoute: typeof TratamientosEquipoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamientosEquipo/': {
      id: '/tratamientosEquipo/'
      path: '/tratamientosEquipo'
      fullPath: '/tratamientosEquipo'
      preLoaderRoute: typeof TratamientosEquipoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theaters/': {
      id: '/theaters/'
      path: '/theaters'
      fullPath: '/theaters'
      preLoaderRoute: typeof TheatersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/': {
      id: '/actors/'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof ActorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamientosEquipo/new': {
      id: '/tratamientosEquipo/new'
      path: '/tratamientosEquipo/new'
      fullPath: '/tratamientosEquipo/new'
      preLoaderRoute: typeof TratamientosEquipoNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamientosEquipo/$id': {
      id: '/tratamientosEquipo/$id'
      path: '/tratamientosEquipo/$id'
      fullPath: '/tratamientosEquipo/$id'
      preLoaderRoute: typeof TratamientosEquipoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theaters/new': {
      id: '/theaters/new'
      path: '/theaters/new'
      fullPath: '/theaters/new'
      preLoaderRoute: typeof TheatersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theaters/$id': {
      id: '/theaters/$id'
      path: '/theaters/$id'
      fullPath: '/theaters/$id'
      preLoaderRoute: typeof TheatersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/new': {
      id: '/movies/new'
      path: '/movies/new'
      fullPath: '/movies/new'
      preLoaderRoute: typeof MoviesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/new': {
      id: '/genres/new'
      path: '/genres/new'
      fullPath: '/genres/new'
      preLoaderRoute: typeof GenresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/$id': {
      id: '/genres/$id'
      path: '/genres/$id'
      fullPath: '/genres/$id'
      preLoaderRoute: typeof GenresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/new': {
      id: '/actors/new'
      path: '/actors/new'
      fullPath: '/actors/new'
      preLoaderRoute: typeof ActorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/$id': {
      id: '/actors/$id'
      path: '/actors/$id'
      fullPath: '/actors/$id'
      preLoaderRoute: typeof ActorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamientosEquipo/$id/': {
      id: '/tratamientosEquipo/$id/'
      path: '/'
      fullPath: '/tratamientosEquipo/$id/'
      preLoaderRoute: typeof TratamientosEquipoIdIndexRouteImport
      parentRoute: typeof TratamientosEquipoIdRoute
    }
    '/theaters/$id/': {
      id: '/theaters/$id/'
      path: '/'
      fullPath: '/theaters/$id/'
      preLoaderRoute: typeof TheatersIdIndexRouteImport
      parentRoute: typeof TheatersIdRoute
    }
    '/movies/$id/': {
      id: '/movies/$id/'
      path: '/'
      fullPath: '/movies/$id/'
      preLoaderRoute: typeof MoviesIdIndexRouteImport
      parentRoute: typeof MoviesIdRoute
    }
    '/genres/$id/': {
      id: '/genres/$id/'
      path: '/'
      fullPath: '/genres/$id/'
      preLoaderRoute: typeof GenresIdIndexRouteImport
      parentRoute: typeof GenresIdRoute
    }
    '/actors/$id/': {
      id: '/actors/$id/'
      path: '/'
      fullPath: '/actors/$id/'
      preLoaderRoute: typeof ActorsIdIndexRouteImport
      parentRoute: typeof ActorsIdRoute
    }
    '/tratamientosEquipo/$id/edit': {
      id: '/tratamientosEquipo/$id/edit'
      path: '/edit'
      fullPath: '/tratamientosEquipo/$id/edit'
      preLoaderRoute: typeof TratamientosEquipoIdEditRouteImport
      parentRoute: typeof TratamientosEquipoIdRoute
    }
    '/theaters/$id/edit': {
      id: '/theaters/$id/edit'
      path: '/edit'
      fullPath: '/theaters/$id/edit'
      preLoaderRoute: typeof TheatersIdEditRouteImport
      parentRoute: typeof TheatersIdRoute
    }
    '/movies/$id/edit': {
      id: '/movies/$id/edit'
      path: '/edit'
      fullPath: '/movies/$id/edit'
      preLoaderRoute: typeof MoviesIdEditRouteImport
      parentRoute: typeof MoviesIdRoute
    }
    '/genres/$id/edit': {
      id: '/genres/$id/edit'
      path: '/edit'
      fullPath: '/genres/$id/edit'
      preLoaderRoute: typeof GenresIdEditRouteImport
      parentRoute: typeof GenresIdRoute
    }
    '/actors/$id/edit': {
      id: '/actors/$id/edit'
      path: '/edit'
      fullPath: '/actors/$id/edit'
      preLoaderRoute: typeof ActorsIdEditRouteImport
      parentRoute: typeof ActorsIdRoute
    }
  }
}

interface ActorsIdRouteChildren {
  ActorsIdEditRoute: typeof ActorsIdEditRoute
  ActorsIdIndexRoute: typeof ActorsIdIndexRoute
}

const ActorsIdRouteChildren: ActorsIdRouteChildren = {
  ActorsIdEditRoute: ActorsIdEditRoute,
  ActorsIdIndexRoute: ActorsIdIndexRoute,
}

const ActorsIdRouteWithChildren = ActorsIdRoute._addFileChildren(
  ActorsIdRouteChildren,
)

interface GenresIdRouteChildren {
  GenresIdEditRoute: typeof GenresIdEditRoute
  GenresIdIndexRoute: typeof GenresIdIndexRoute
}

const GenresIdRouteChildren: GenresIdRouteChildren = {
  GenresIdEditRoute: GenresIdEditRoute,
  GenresIdIndexRoute: GenresIdIndexRoute,
}

const GenresIdRouteWithChildren = GenresIdRoute._addFileChildren(
  GenresIdRouteChildren,
)

interface MoviesIdRouteChildren {
  MoviesIdEditRoute: typeof MoviesIdEditRoute
  MoviesIdIndexRoute: typeof MoviesIdIndexRoute
}

const MoviesIdRouteChildren: MoviesIdRouteChildren = {
  MoviesIdEditRoute: MoviesIdEditRoute,
  MoviesIdIndexRoute: MoviesIdIndexRoute,
}

const MoviesIdRouteWithChildren = MoviesIdRoute._addFileChildren(
  MoviesIdRouteChildren,
)

interface TheatersIdRouteChildren {
  TheatersIdEditRoute: typeof TheatersIdEditRoute
  TheatersIdIndexRoute: typeof TheatersIdIndexRoute
}

const TheatersIdRouteChildren: TheatersIdRouteChildren = {
  TheatersIdEditRoute: TheatersIdEditRoute,
  TheatersIdIndexRoute: TheatersIdIndexRoute,
}

const TheatersIdRouteWithChildren = TheatersIdRoute._addFileChildren(
  TheatersIdRouteChildren,
)

interface TratamientosEquipoIdRouteChildren {
  TratamientosEquipoIdEditRoute: typeof TratamientosEquipoIdEditRoute
  TratamientosEquipoIdIndexRoute: typeof TratamientosEquipoIdIndexRoute
}

const TratamientosEquipoIdRouteChildren: TratamientosEquipoIdRouteChildren = {
  TratamientosEquipoIdEditRoute: TratamientosEquipoIdEditRoute,
  TratamientosEquipoIdIndexRoute: TratamientosEquipoIdIndexRoute,
}

const TratamientosEquipoIdRouteWithChildren =
  TratamientosEquipoIdRoute._addFileChildren(TratamientosEquipoIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  ActorsIdRoute: ActorsIdRouteWithChildren,
  ActorsNewRoute: ActorsNewRoute,
  GenresIdRoute: GenresIdRouteWithChildren,
  GenresNewRoute: GenresNewRoute,
  MoviesIdRoute: MoviesIdRouteWithChildren,
  MoviesNewRoute: MoviesNewRoute,
  TheatersIdRoute: TheatersIdRouteWithChildren,
  TheatersNewRoute: TheatersNewRoute,
  TratamientosEquipoIdRoute: TratamientosEquipoIdRouteWithChildren,
  TratamientosEquipoNewRoute: TratamientosEquipoNewRoute,
  ActorsIndexRoute: ActorsIndexRoute,
  GenresIndexRoute: GenresIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  TheatersIndexRoute: TheatersIndexRoute,
  TratamientosEquipoIndexRoute: TratamientosEquipoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
